Fixed printf that starts with minus sign in clientStat.sh
pivpn/pivpn pull request #1661
Opened 2022-11-30 21:23 UTC by astroganga

At line 53 of clientStat.sh there is a printf that starts with minus sign

`  52           printf "  \t  %s %s %s " "${array[7]}" "${array[8]}" "${array[10]}"
  53           printf "- %s\n" "${array[9]}"
  54           printf "\n"
`
When **pivpn clients** command is executed the minus sign is interpreted as an option and the script fails by not printing the connection time.

I fixed the issue adding -- before the format string to disarm the minus sign.

`  52           printf "  \t  %s %s %s " "${array[7]}" "${array[8]}" "${array[10]}"
  53           printf -- "- %s\n" "${array[9]}"
  54           printf "\n"
`

Hope this helps.
Thanks
Bye.

2022-11-30 23:06 UTC, 4s3ti requested changes
Once again thanks a lot for your PR, after a proper review, please check my comments regarding the code itself. 

Also please amend your commit message to be according to the commit rules. 

In this situation the way I would do it is: 

* `git reset HEAD~1` 
* make the suggested code changes
* `git commit` 

The header of the commit should be: fix(scripts): fix clientstat.sh
The commit body should be (for example): show correct information and fix error caused by dash on printf

should look something like: 

```
fix(scripts): clientstat.sh

show correct information and fix error caused by dash on printf
```
* `git push origin master --force`


Please note the suggestion is just one way of doing it, feel free to use any method that feels better for you.

2022-11-30 23:31 UTC, astroganga commented
On my system the output with my fix is the following:

`Dec 1 2022 - 00:14:15`

If I remove `"${array[8]}"` and `"${array[9]}"` the output is wrong.

This is my output with your fix:

`Thu Dec`

I am on stable now. I need to switch on testing to verify if there are differences.

2022-11-30 23:32 UTC, astroganga commented on scripts/openvpn/clientStat.sh
>            printf "\n"
On my system the output with my fix is the following:

`Dec 1 2022 - 00:14:15`

If I remove `"${array[8]}"` and `"${array[9]}"` the output is wrong.

This is my output with your fix:

`Thu Dec`

I am on stable now. I need to switch on testing to verify if there are differences.

2022-11-30 23:38 UTC, 4s3ti commented
hmm crap ... don't think changing from stable to test will change anything, it seems the openvpn-status.log saves data based on some regional settings which affects the position of the array where the data ends up =/  this kind of "parsing" is always messy =/ 

then I say it might be better to just remove the dash, and some day if i have the time I might try to find a better way to parse the log file.

2022-11-30 23:48 UTC, astroganga commented
Ok. If you agree I will adjust the fix removing the dash on line 53:

`printf " %s\n" "${array[9]}"`

without touching array order. If some are empty I don't think will be an issue and at the same time we will not lose information on other regional settings.

I will do it tomorrow as it is too late for me now.
Thanks

2022-12-01 08:55 UTC, 4s3ti commented
yeah its fine, just remove the dash. 

On my case (using aws ec2 instnace), it was actually returning meaningless data.

2022-12-01 10:47 UTC, 4s3ti approved these changes

2022-12-01 10:48 UTC, merged

2022-12-01 10:48 UTC, 4s3ti commented
Done, thanks a lot :D

2022-12-01 10:52 UTC, 4s3ti commented
:tada: This PR is included in version 4.1.6-test.1 :tada:

The release is available on [GitHub release](https://github.com/pivpn/pivpn/releases/tag/v4.1.6-test.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-16 01:04 UTC, 4s3ti commented
:tada: This PR is included in version 4.2.0 :tada:

The release is available on [GitHub release](https://github.com/pivpn/pivpn/releases/tag/v4.2.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: